### ISSUE TITLE
ImportError: No module named pexpect

### ISSUE THREAD

**Issue by youxiaojie** [thispc/psiphon#21]
Traceback (most recent call last):
  File "psi_client.py", line 22, in <module>
    from psi_ssh_connection import SSHConnection, OSSHConnection
  File "/media/allan/home_data/psiphon/psiphon-circumvention-system-155a35fc9106/pyclient/psi_ssh_connection.py", line 21, in <module>
    import pexpect
ImportError: No module named pexpect

**Comment by thispc** [comment]
`sudo pip install pexpect`
