### ISSUE TITLE
Decoding error when updating servers

### ISSUE THREAD

**Issue by sunandabansal** [thispc/psiphon#31]
I get the following error when I try to update servers using `python psi_client.py -u
` - 
```python
100% [..........................................................................] 1450949 / 1450949Traceback (most recent call last):
  File "psi_client.py", line 440, in <module>
    update()
  File "psi_client.py", line 311, in update
    js = i[loc:].decode('hex')
  File "/home/username/anaconda3/envs/py27/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Odd-length string
```

I am not quite sure what is causing it. Can you please suggest a solution?

**Comment by crisdeodates** [comment]
Same error occurred for me too.

**Comment by sunandabansal** [comment]
I am sorry I didn't check the existing issues. Thank you for helping me out.
