### ISSUE TITLE
DEBUG: OSSH connection: End Of File (EOF). Exception style platform.

### ISSUE THREAD

**Issue by amid11** [thispc/psiphon#4]
I just can connect to GB servers, If I try to connect to any other servers than GB's I get this error:
```
[root@root psiphon]$ psiphon -a -r US
Trying to connect to US : 104.237.147.191
DEBUG: OSSH connection: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7f77bbc7e3d0>
command: ./ssh 
args: [u'./ssh', u'-C', u'-D', u'127.0.0.1:1080', u'-N', u'-p', u'53', u'-z', u'-Z', u'd2fb4d55c5d000056b9efed5bff5270f91c377bf7dc08a2912bb087a04b9ef3b', u'psiphon_ssh_ebf2e786ed2c97bf@104.237.147.191']
buffer (last 100 chars): ''
before (last 100 chars): 'ssh_exchange_identification: read: Connection reset by peer\r\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 255
flag_eof: True
pid: 4932
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("fb:9c:d3:fe:0a:5e:a9:16:1c:d2:68:bf:81:ae:55:04")
    1: re.compile("Password:")
Trying next server...
```
and it goes on and on then it just froze on a server which made me to terminate the process by pressing Ctrl + C, I get this output:
```
^CTraceback (most recent call last):
  File "psi_client.py", line 465, in <module>
    connect(False)
  File "psi_client.py", line 271, in connect
    print 'DEBUG: %s connection: %s' % (relay, str(error))
KeyboardInterrupt
```
thank you so much,
Amid

**Comment by thispc** [comment]
Only GB servers are working from their end.
However , NL servers are working too.
